name: Build LOVE Package
description: Archives game folder into a .love file
inputs:
  output_folder:
    description: The folder in which the generated .love file will be placed
    required: true
  product_file:
    description: The basename of the file to be generated
    required: true
  product_name:
    description: The name of the game
    required: true
runs:
  using: composite
  steps:
    - name: Install tools
      uses: ./.github/actions/install-tools
    - name: Build LOVE package
      shell: bash
      run: |
        # Create a temporary copy of the game directory for build
        mkdir -p "./builds/temp"
        cp -r ./game/* "./builds/temp/"

        # Remove debug-related code from main.lua
        sed -i '/if Settings.IS_DEBUG_ENABLED then/,/^  end$/d' "./builds/temp/main.lua"

        # Remove overlayStats.lua file
        rm -f "./builds/temp/lib/overlayStats.lua"

        7z a -tzip -mx=6 -mpass=15 -mtc=off \
        "${{ inputs.output_folder }}/${{ inputs.product_file }}.love" \
        ./builds/temp/* -xr!.gitkeep

        # Clean up temporary directory
        rm -rf "./builds/temp"
